version: '3.9'

services:
  mongodb:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: mi

volumes:
  mongodb_data:
    driver: local # Sử dụng volume local
